In [1]:
import dabench as dab
import numpy as np
import jax
from timeit import default_timer as timer
import pickle
import pandas as pd
import matplotlib.pyplot as plt

from ray import train, tune
from hyperopt import hp
from ray.tune.search.hyperopt import HyperOptSearch

In [2]:
%%bash
mkdir -p out_rev/l96

# Define parameters

In [3]:
system_dim= 36
spinup_size = 14400
valid_size = 5000
test_size = 5000
nr_steps = spinup_size + valid_size + test_size
delta_t=0.01
obs_sd = 0.5
sigma_bg = 0.3
sigma_obs = 0.625
analysis_window = 0.1
analysis_time_in_window = 0.0
obs_location_count = 18
random_seed = 5
num_iters = 3
n_outer_loops = 3

In [4]:
def calc_background_cov(enkf_run_pkl):
    with open(enkf_run_pkl, 'rb') as f: 
        etkf_run = pickle.load(f) 
    system_dim = etkf_run.values.shape[-1]
    etkf_errors = np.moveaxis(etkf_run.values, (0,1,2), (1,0,2)) - np.mean(etkf_run.values, axis=1)
    etkf_errors = etkf_errors[:,-5000:]
    etkf_errors = etkf_errors[:,np.arange(9,5000,10)]
    B = np.cov(etkf_errors.reshape(system_dim, -1))
    return B

# Function definition: Backprop 4DVar

We'll need to prep and run Backprop-4DVar many times, so this wraps it all into one function

In [5]:
def run_backprop_4dvar(system_dim, nr_steps, spinup_size, valid_size, test_size, 
                       test_run, delta_t, obs_location_count, obs_sd, sigma_bg_mult, 
                       sigma_obs, analysis_window, analysis_time_in_window, 
                       random_seed, num_iters, learning_rate, lr_decay,
                       enkf_run_pkl):
    np_rng = np.random.default_rng(random_seed)
    jax.clear_caches()

    ### Nature Run
    nature_run = dab.data.Lorenz96(system_dim=system_dim, delta_t=delta_t,
                                   store_as_jax=True, random_seed=random_seed)

    x0_initial = np_rng.normal(size=system_dim, scale=1)
    nature_run.generate(n_steps=nr_steps, x0 = x0_initial) 
    nr_spinup, nr_valid, nr_test = nature_run.split_train_valid_test(
        spinup_size, valid_size, test_size)

    if not test_run:
        nr_eval = nr_valid
    else:
        nr_eval = nr_test


    ### Observations
    obs_l96 = dab.observer.Observer(
        nr_eval,
        time_indices = np.arange(0, nr_eval.time_dim, 5),
        random_location_count = obs_location_count,
        error_bias = 0.0,
        error_sd = obs_sd,
        random_seed=random_seed,
        stationary_observers=True,
        store_as_jax=True
    )
    obs_vec_l96 = obs_l96.observe()

    
    ### Forecast Model
    model_l96 = dab.data.Lorenz96(system_dim=system_dim, delta_t=delta_t, 
                                  store_as_jax=True, random_seed=random_seed)

    class L96Model(dab.model.Model):                                                                       
        """Defines model wrapper for Lorenz96 to test forecasting."""
        def forecast(self, state_vec, n_steps):
            self.model_obj.generate(x0=state_vec.values, n_steps=n_steps)
            new_vals = self.model_obj.values 

            new_vec = dab.vector.StateVector(values=new_vals, store_as_jax=True)

            return new_vec

    fc_model = L96Model(model_obj=model_l96)
    
    ### Set up DA matrices: H (observation), R (obs error), B (background error)
    H = np.zeros((obs_location_count, system_dim))
    H[np.arange(H.shape[0]), obs_vec_l96.location_indices[0]] = 1
    R = (sigma_obs**2)* np.identity(obs_location_count)
    # B = (sigma_bg**2)*np.identity(system_dim)
    B = sigma_bg_mult*calc_background_cov(enkf_run_pkl)

    
    ### Run data assimilation
    da_time_start = timer()
    
    # Prep DA object
    dc = dab.dacycler.Var4DBackprop(
        system_dim=system_dim,
        delta_t=nr_eval.delta_t,
        H=H,
        B=B,
        R=R,
        num_iters=num_iters,
        loss_growth_limit=5,
        learning_rate=learning_rate,
        lr_decay=lr_decay,
        model_obj=fc_model,
        obs_window_indices=[0,5,10],
        steps_per_window=11, # 11 instead of 10 because inclusive of 0 and 11
        )

    # Generate initial conditions
    cur_tstep = 0
    x0_original = nr_eval.values[cur_tstep] + np_rng.normal(size=(system_dim,), 
                                                            scale=np.diagonal(B))
    x0_sv = dab.vector.StateVector(
        values=x0_original,
        store_as_jax=True)
    
    # Execute
    out_statevec = dc.cycle(
        input_state = x0_sv,
        start_time = nr_eval.times[cur_tstep],
        obs_vector = obs_vec_l96,
        analysis_window=analysis_window,
        n_cycles=498,
        return_forecast=True,
        obs_error_sd=sigma_obs,
        analysis_time_in_window=analysis_time_in_window)
    
    da_time = timer()-da_time_start
    rmse = np.sqrt(np.mean(np.square(nr_eval.values[:-20] - out_statevec.values)))
    
    return out_statevec, rmse, obs_vec_l96, nr_eval, da_time

# Hyperparameter optimization on validation set

Using RayTune to optimize alpha (learning rate) and alpha decay

In [6]:
def train_backprop_4dvar(config, system_dim, num_obs, obs_sd):
    """A wrapper for RayTune to run backprop 4Dvar"""
    random_seed = system_dim 
    obs_location_count = num_obs
    enkf_run_pkl = '/home/ksolvik/research/da/CompareOld/DataAssimBench-Examples/examples/da_cycler/Solvik_Penny_Hoyer_2024-Backprop4DVar/out_rev/l96/l96_enkf_statevec_{}dim_v1.pkl'.format(system_dim)
    run_dict = dict(
        system_dim=system_dim, 
        nr_steps=nr_steps,
        spinup_size=spinup_size,
        valid_size=valid_size,
        test_size=test_size,
        test_run=False,
        delta_t=delta_t,
        obs_location_count=obs_location_count,
        obs_sd=obs_sd,
        sigma_bg_mult=5*obs_sd,
        sigma_obs=obs_sd,
        analysis_window=analysis_window,
        analysis_time_in_window=analysis_time_in_window,
        random_seed=random_seed,
        num_iters=num_iters,
        learning_rate=0,
        lr_decay=0,
        enkf_run_pkl=enkf_run_pkl)

    run_dict['learning_rate'] = config['lr']
    run_dict['lr_decay'] = config['lr_decay']
    
    out_bp, error_bp, obs_vec_l96, nr_eval, da_time = run_backprop_4dvar(**run_dict)
    
    train.report({'rmse':error_bp})

### System size experiments

In [7]:
# Define search space
space = {
    "lr": hp.loguniform("lr", -5, 0),
    "lr_decay": hp.uniform("lr_decay", 0.1, 0.99),
}

In [8]:
all_results_df_list = []
system_dim_list = [6, 20, 36, 72, 144, 256]

for system_dim in system_dim_list:
    tune_time_start = timer()
    
    trainable_with_system_dim = tune.with_parameters(train_backprop_4dvar, 
                                                     system_dim=system_dim,
                                                     num_obs=int(system_dim/2),
                                                     obs_sd=0.5
                                                     )
    
    hyperopt_search = HyperOptSearch(space, metric="rmse", mode="min", random_state_seed=random_seed)
    tuner = tune.Tuner(
        trainable_with_system_dim,
        tune_config=tune.TuneConfig(
            num_samples=50,
            max_concurrent_trials=4,
            search_alg=hyperopt_search
        ),
    )
    
    results = tuner.fit()

    cur_results_df = results.get_dataframe()
    cur_results_df['system_dim'] = system_dim
    tune_time = timer() - tune_time_start
    cur_results_df['total_tune_time'] = tune_time

    all_results_df_list.append(cur_results_df)

2024-11-19 08:47:04,472	ERROR tune_controller.py:1331 -- Trial task failed for trial train_backprop_4dvar_61a8c910
Traceback (most recent call last):
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
             ^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/_private/worker.py", line 2691, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/_private/worker.py", line 871, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(XlaRuntimeError): ray::ImplicitFunc.train() (pid=189934, ip=127.0.0.1, actor_id=f4f4c617c2bba12d20bf51e901000000, repr=train_backprop_4dvar)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/air/_internal/util.py", line 104, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 250, in _trainable_func
    output = fn()
             ^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_135422/1232265654.py", line 29, in train_backprop_4dvar
  File "/tmp/ipykernel_135422/4176834579.py", line 90, in run_backprop_4dvar
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/dacycler/_var4d_backprop.py", line 438, in cycle
    return vector.StateVector(values=jnp.concatenate(all_values),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/vector/_state_vector.py", line 49, in __init__
    super().__init__(time_dim=time_dim,
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/vector/_vector.py", line 28, in __init__
    self.values = values
    ^^^^^^^^^^^
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/vector/_vector.py", line 73, in values
    self._values = np.asarray(vals)
                   ^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/array.py", line 414, in __array__
    return np.asarray(self._value, dtype=dtype, **kwds)
                      ^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/profiler.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/array.py", line 613, in _value
    self._npy_value = self._single_device_array_to_np_array()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: Buffer Definition Event: Error dispatching computation: %sCpuCallback error: Traceback (most recent call last):
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/interpreters/mlir.py", line 2777, in _wrapped_callback
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/debugging.py", line 159, in _callback
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/debugging.py", line 95, in debug_callback_impl
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/debugging.py", line 262, in _flat_callback
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/dacycler/_var4d_backprop.py", line 117, in _raise_loss_growth_error
ValueError: Loss value has exceeded self.loss_growth_limit, exiting optimization
2024-11-19 08:47:28,055	ERROR tune_controller.py:1331 -- Trial task failed for trial train_backprop_4dvar_5d499913
Traceback (most recent call last):
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
             ^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/_private/worker.py", line 2691, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/_private/worker.py", line 871, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(XlaRuntimeError): ray::ImplicitFunc.train() (pid=190535, ip=127.0.0.1, actor_id=6a629da0d1e0a090a0c4728101000000, repr=train_backprop_4dvar)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/air/_internal/util.py", line 104, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 250, in _trainable_func
    output = fn()
             ^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_135422/1232265654.py", line 29, in train_backprop_4dvar
  File "/tmp/ipykernel_135422/4176834579.py", line 90, in run_backprop_4dvar
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/dacycler/_var4d_backprop.py", line 438, in cycle
    return vector.StateVector(values=jnp.concatenate(all_values),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/vector/_state_vector.py", line 49, in __init__
    super().__init__(time_dim=time_dim,
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/vector/_vector.py", line 28, in __init__
    self.values = values
    ^^^^^^^^^^^
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/vector/_vector.py", line 73, in values
    self._values = np.asarray(vals)
                   ^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/array.py", line 414, in __array__
    return np.asarray(self._value, dtype=dtype, **kwds)
                      ^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/profiler.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/array.py", line 613, in _value
    self._npy_value = self._single_device_array_to_np_array()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: Buffer Definition Event: Error dispatching computation: %sCpuCallback error: Traceback (most recent call last):
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/interpreters/mlir.py", line 2777, in _wrapped_callback
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/debugging.py", line 159, in _callback
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/debugging.py", line 95, in debug_callback_impl
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/debugging.py", line 262, in _flat_callback
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/dacycler/_var4d_backprop.py", line 117, in _raise_loss_growth_error
ValueError: Loss value has exceeded self.loss_growth_limit, exiting optimization
2024-11-19 08:47:36,509	ERROR tune_controller.py:1331 -- Trial task failed for trial train_backprop_4dvar_66a58443
Traceback (most recent call last):
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
             ^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/_private/worker.py", line 2691, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/_private/worker.py", line 871, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(XlaRuntimeError): ray::ImplicitFunc.train() (pid=190694, ip=127.0.0.1, actor_id=c72949baaf2fbfa4cbd4089301000000, repr=train_backprop_4dvar)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/air/_internal/util.py", line 104, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 250, in _trainable_func
    output = fn()
             ^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_135422/1232265654.py", line 29, in train_backprop_4dvar
  File "/tmp/ipykernel_135422/4176834579.py", line 90, in run_backprop_4dvar
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/dacycler/_var4d_backprop.py", line 438, in cycle
    return vector.StateVector(values=jnp.concatenate(all_values),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/vector/_state_vector.py", line 49, in __init__
    super().__init__(time_dim=time_dim,
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/vector/_vector.py", line 28, in __init__
    self.values = values
    ^^^^^^^^^^^
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/vector/_vector.py", line 73, in values
    self._values = np.asarray(vals)
                   ^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/array.py", line 414, in __array__
    return np.asarray(self._value, dtype=dtype, **kwds)
                      ^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/profiler.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/array.py", line 613, in _value
    self._npy_value = self._single_device_array_to_np_array()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: Buffer Definition Event: Error dispatching computation: %sCpuCallback error: Traceback (most recent call last):
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/interpreters/mlir.py", line 2777, in _wrapped_callback
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/debugging.py", line 159, in _callback
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/debugging.py", line 95, in debug_callback_impl
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/debugging.py", line 262, in _flat_callback
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/dacycler/_var4d_backprop.py", line 117, in _raise_loss_growth_error
ValueError: Loss value has exceeded self.loss_growth_limit, exiting optimization
2024-11-19 08:49:34,968	ERROR tune_controller.py:1331 -- Trial task failed for trial train_backprop_4dvar_b5f11f34
Traceback (most recent call last):
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
             ^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/_private/worker.py", line 2691, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/_private/worker.py", line 871, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(XlaRuntimeError): ray::ImplicitFunc.train() (pid=193826, ip=127.0.0.1, actor_id=7da4bc17b498cf309f26a5e101000000, repr=train_backprop_4dvar)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/air/_internal/util.py", line 104, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 250, in _trainable_func
    output = fn()
             ^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_135422/1232265654.py", line 29, in train_backprop_4dvar
  File "/tmp/ipykernel_135422/4176834579.py", line 90, in run_backprop_4dvar
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/dacycler/_var4d_backprop.py", line 438, in cycle
    return vector.StateVector(values=jnp.concatenate(all_values),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/vector/_state_vector.py", line 49, in __init__
    super().__init__(time_dim=time_dim,
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/vector/_vector.py", line 28, in __init__
    self.values = values
    ^^^^^^^^^^^
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/vector/_vector.py", line 73, in values
    self._values = np.asarray(vals)
                   ^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/array.py", line 414, in __array__
    return np.asarray(self._value, dtype=dtype, **kwds)
                      ^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/profiler.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/array.py", line 613, in _value
    self._npy_value = self._single_device_array_to_np_array()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: Buffer Definition Event: Error dispatching computation: %sCpuCallback error: Traceback (most recent call last):
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/interpreters/mlir.py", line 2777, in _wrapped_callback
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/debugging.py", line 159, in _callback
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/debugging.py", line 95, in debug_callback_impl
  File "/home/ksolvik/miniconda3/envs/dab-old/lib/python3.11/site-packages/jax/_src/debugging.py", line 262, in _flat_callback
  File "/home/ksolvik/research/da/CompareOld/DataAssimBench/dabench/dacycler/_var4d_backprop.py", line 117, in _raise_loss_growth_error
ValueError: Loss value has exceeded self.loss_growth_limit, exiting optimization

In [9]:

full_results_df = pd.concat(all_results_df_list)

In [ ]:
full_results_df = pd.concat(all_results_df_list)
full_results_df.to_csv('./out_rev/l96/raytune_l96_v2.csv')

In [11]:
full_results_df[['system_dim','rmse']].groupby('system_dim').min()

                rmse
system_dim
6           0.334454
20          0.367673
36          0.362694
72          0.698850
144         0.786066
256         0.783144

### Experiments varying number of observations and obs error

In [12]:
space = {
    "lr": hp.loguniform("lr", -5, 0),
    "lr_decay": hp.uniform("lr_decay", 0.1, 0.99),
}

In [13]:
all_results_df_list = []

system_dim = 36
num_obs_list = [6, 12, 18, 24, 30, 36]
obs_error_list = [0.1, 0.2, 0.3, 0.4, 0.5, 0.75, 1.0, 1.5, 2.0]

for obs_location_count in num_obs_list:
    for obs_sd in obs_error_list:
        tune_time_start = timer()
        
        trainable_with_system_dim = tune.with_parameters(train_backprop_4dvar, 
                                                         system_dim=system_dim,
                                                         num_obs=obs_location_count,
                                                         obs_sd=obs_sd
                                                         )

        hyperopt_search = HyperOptSearch(space, metric="rmse", mode="min", random_state_seed=random_seed)
        tuner = tune.Tuner(
            trainable_with_system_dim,
            tune_config=tune.TuneConfig(
                num_samples=20,
                max_concurrent_trials=4,
                search_alg=hyperopt_search
            ),
        )
        
        results = tuner.fit()

        cur_results_df = results.get_dataframe()
        cur_results_df['system_dim'] = system_dim
        cur_results_df['num_obs'] = obs_location_count
        cur_results_df['obs_sd'] = obs_sd
        tune_time = timer() - tune_time_start
        cur_results_df['total_tune_time'] = tune_time
        
        all_results_df_list.append(cur_results_df)

2024-11-19 11:03:58,315	INFO tune.py:1009 -- Wrote the latest version of all result files and experiment state to '/home/ksolvik/ray_results/train_backprop_4dvar_2024-11-19_11-01-23' in 0.0128s.
2024-11-19 11:03:58,328	INFO tune.py:1041 -- Total run time: 154.48 seconds (154.42 seconds for the tuning loop).

In [ ]:
full_results_df = pd.concat(all_results_df_list)
full_results_df.to_csv('./out_rev/l96/raytune_l96_heatmap_v2.csv')

In [16]:
full_results_df.groupby(['num_obs', 'obs_sd']).min('rmse')

                    rmse   timestamp   done  training_iteration  \
num_obs obs_sd
6       0.10    3.036042  1732031585  False                   1
        0.20    3.274274  1732031728  False                   1
        0.30    3.252550  1732031869  False                   1
        0.40    3.324765  1732032014  False                   1
        0.50    3.325785  1732032156  False                   1
        0.75    3.461627  1732032288  False                   1
        1.00    3.554428  1732032431  False                   1
        1.50    3.761772  1732032575  False                   1
        2.00    3.810311  1732032725  False                   1
12      0.10    0.417158  1732032869  False                   1
        0.20    0.851675  1732033012  False                   1
        0.30    0.984368  1732033156  False                   1
        0.40    1.383614  1732033299  False                   1
        0.50    1.181133  1732033441  False                   1
        0.75    1.578991  1732033584  False                   1
        1.00    1.742215  1732033727  False                   1
        1.50    2.403930  1732033869  False                   1
        2.00    2.698930  1732034011  False                   1
18      0.10    0.064410  1732034157  False                   1
        0.20    0.134558  1732034301  False                   1
        0.30    0.209870  1732034442  False                   1
        0.40    0.292539  1732034584  False                   1
        0.50    0.362694  1732034729  False                   1
        0.75    0.556285  1732034874  False                   1
        1.00    0.772573  1732035036  False                   1
        1.50    1.347618  1732035227  False                   1
        2.00    1.693329  1732035383  False                   1
24      0.10    0.074079  1732035525  False                   1
        0.20    0.142474  1732035669  False                   1
        0.30    0.209081  1732035808  False                   1
        0.40    0.396906  1732035950  False                   1
        0.50    0.428863  1732036095  False                   1
        0.75    0.626642  1732036242  False                   1
        1.00    0.735961  1732036393  False                   1
        1.50    1.065805  1732036540  False                   1
        2.00    1.342257  1732036683  False                   1
30      0.10    0.041308  1732036834  False                   1
        0.20    0.078662  1732036959  False                   1
        0.30    0.121158  1732037095  False                   1
        0.40    0.163560  1732037241  False                   1
        0.50    0.206518  1732037384  False                   1
        0.75    0.313093  1732037524  False                   1
        1.00    0.416419  1732037676  False                   1
        1.50    0.630129  1732037828  False                   1
        2.00    0.846035  1732037975  False                   1
36      0.10    0.032327  1732038123  False                   1
        0.20    0.065501  1732038271  False                   1
        0.30    0.097298  1732038416  False                   1
        0.40    0.132306  1732038563  False                   1
        0.50    0.167008  1732038709  False                   1
        0.75    0.254294  1732038853  False                   1
        1.00    0.344508  1732039001  False                   1
        1.50    0.516207  1732039150  False                   1
        2.00    0.683837  1732039305  False                   1

                time_this_iter_s  time_total_s     pid  time_since_restore  \
num_obs obs_sd
6       0.10           12.957392     12.957392  199672           12.957392
        0.20           12.898589     12.898589  203425           12.898589
        0.30           13.083008     13.083008  207010           13.083008
        0.40           12.849288     12.849288  210648           12.849288
        0.50           11.357412     11.357412  214430           11.357412
        0.75           13.397961     13.397961  218047           13.397961
        1.00           13.344967     13.344967  221745           13.344967
        1.50           13.811332     13.811332  225352           13.811332
        2.00           13.481391     13.481391  229875           13.481391
12      0.10           12.937717     12.937717  233462           12.937717
        0.20           13.333791     13.333791  237066           13.333791
        0.30           12.987784     12.987784  240629           12.987784
        0.40           11.940471     11.940471  244354           11.940471
        0.50           12.871964     12.871964  248249           12.871964
        0.75           13.897050     13.897050  252319           13.897050
        1.00           13.093993     13.093993  256070           13.093993
        1.50           13.461228     13.461228  259846           13.461228
        2.00           13.563633     13.563633  263479           13.563633
18      0.10           12.794135     12.794135  267502           12.794135
        0.20           12.679268     12.679268  271252           12.679268
        0.30           12.630838     12.630838  274858           12.630838
        0.40           13.105165     13.105165  278452           13.105165
        0.50           13.464317     13.464317  282258           13.464317
        0.75           13.797230     13.797230  285961           13.797230
        1.00           19.786367     19.786367  290507           19.786367
        1.50           13.236036     13.236036  294239           13.236036
        2.00           13.350064     13.350064  298273           13.350064
24      0.10           12.724656     12.724656  302183           12.724656
        0.20           12.465916     12.465916  306177           12.465916
        0.30           12.612922     12.612922  309850           12.612922
        0.40           12.317042     12.317042  313538           12.317042
        0.50           13.386586     13.386586  317247           13.386586
        0.75           13.312154     13.312154  321370           13.312154
        1.00           13.347689     13.347689  325460           13.347689
        1.50           11.768752     11.768752  329741           11.768752
        2.00           13.621337     13.621337  333922           13.621337
30      0.10           10.908584     10.908584  338381           10.908584
        0.20           10.931019     10.931019  342009           10.931019
        0.30           13.061979     13.061979  345722           13.061979
        0.40           13.120360     13.120360  349577           13.120360
        0.50           12.766834     12.766834  353185           12.766834
        0.75           13.301908     13.301908  356937           13.301908
        1.00           14.403251     14.403251  361204           14.403251
        1.50           13.705684     13.705684  365490           13.705684
        2.00           14.068571     14.068571  369275           14.068571
36      0.10           13.196667     13.196667  373082           13.196667
        0.20           12.676646     12.676646  378378           12.676646
        0.30           13.115849     13.115849  383444           13.115849
        0.40           13.019547     13.019547  387167           13.019547
        0.50           12.586621     12.586621  391212           12.586621
        0.75           12.995718     12.995718  394969           12.995718
        1.00           13.657120     13.657120  399300           13.657120
        1.50           13.604248     13.604248  403676           13.604248
        2.00           14.515934     14.515934  408188           14.515934

                iterations_since_restore  config/lr  config/lr_decay  \
num_obs obs_sd
6       0.10                           1   0.006848         0.129514
        0.20                           1   0.006848         0.129514
        0.30                           1   0.006848         0.157568
        0.40                           1   0.006848         0.157568
        0.50                           1   0.006848         0.129514
        0.75                           1   0.006848         0.129514
        1.00                           1   0.006848         0.129514
        1.50                           1   0.006848         0.129514
        2.00                           1   0.006848         0.129514
12      0.10                           1   0.006848         0.129514
        0.20                           1   0.006848         0.129514
        0.30                           1   0.006848         0.157568
        0.40                           1   0.006848         0.129514
        0.50                           1   0.006848         0.157568
        0.75                           1   0.006848         0.129514
        1.00                           1   0.006848         0.129514
        1.50                           1   0.006848         0.129514
        2.00                           1   0.006848         0.129514
18      0.10                           1   0.006848         0.129514
        0.20                           1   0.006848         0.129514
        0.30                           1   0.006848         0.129514
        0.40                           1   0.006848         0.157568
        0.50                           1   0.006848         0.157568
        0.75                           1   0.006848         0.129514
        1.00                           1   0.006848         0.129514
        1.50                           1   0.006848         0.129514
        2.00                           1   0.006848         0.129514
24      0.10                           1   0.006848         0.129514
        0.20                           1   0.006848         0.129514
        0.30                           1   0.006848         0.129514
        0.40                           1   0.006848         0.129514
        0.50                           1   0.006848         0.129514
        0.75                           1   0.006848         0.129514
        1.00                           1   0.006848         0.129514
        1.50                           1   0.006848         0.129514
        2.00                           1   0.006848         0.129514
30      0.10                           1   0.006848         0.129514
        0.20                           1   0.006848         0.129514
        0.30                           1   0.006848         0.129514
        0.40                           1   0.006848         0.157568
        0.50                           1   0.006848         0.129514
        0.75                           1   0.006848         0.129514
        1.00                           1   0.006848         0.129514
        1.50                           1   0.006848         0.129514
        2.00                           1   0.006848         0.129514
36      0.10                           1   0.006848         0.129514
        0.20                           1   0.006848         0.129514
        0.30                           1   0.006848         0.129514
        0.40                           1   0.006848         0.157568
        0.50                           1   0.006848         0.157568
        0.75                           1   0.006848         0.129514
        1.00                           1   0.006848         0.129514
        1.50                           1   0.006848         0.129514
        2.00                           1   0.006848         0.129514

                system_dim  total_tune_time
num_obs obs_sd
6       0.10            36       142.697696
        0.20            36       141.910679
        0.30            36       144.190475
        0.40            36       144.187563
        0.50            36       130.302086
        0.75            36       142.442745
        1.00            36       141.128524
        1.50            36       152.583521
        2.00            36       143.745528
12      0.10            36       143.708248
        0.20            36       143.899600
        0.30            36       142.119593
        0.40            36       143.810374
        0.50            36       142.161048
        0.75            36       143.753840
        1.00            36       141.435861
        1.50            36       141.619413
        2.00            36       145.690757
18      0.10            36       143.600057
        0.20            36       143.054073
        0.30            36       141.449134
        0.40            36       144.228982
        0.50            36       145.126929
        0.75            36       150.821943
        1.00            36       193.589435
        1.50            36       164.631054
        2.00            36       140.730678
24      0.10            36       144.946073
        0.20            36       140.340082
        0.30            36       141.636257
        0.40            36       143.404231
        0.50            36       146.664278
        0.75            36       150.326997
        1.00            36       147.216808
        1.50            36       144.172378
        2.00            36       149.669973
30      0.10            36       129.822978
        0.20            36       132.639733
        0.30            36       145.993277
        0.40            36       142.437473
        0.50            36       142.174736
        0.75            36       149.771706
        1.00            36       152.309143
        1.50            36       147.078149
        2.00            36       148.873238
36      0.10            36       147.329439
        0.20            36       145.065231
        0.30            36       147.888976
        0.40            36       145.644553
        0.50            36       144.673835
        0.75            36       146.753699
        1.00            36       148.448439
        1.50            36       154.416175
        2.00            36       154.549931